/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.targosz.invoicing

import spock.lang.Specification

class InvoicingSystemApplicationTest extends Specification {

    def app = new InvoicingSystemApplication()

    def "application init check"() {
        setup:
        def app = new InvoicingSystemApplication()

        expect:
        app.main()
    }

}
