/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package pl.targosz.invoicing;

import java.io.IOException;


public class App {

    public static void main(String[] args) throws IOException {


    }
}

