/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package pl.targosz.invoicing;

import java.io.IOException;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class InvoicingSystemApplication {

    public static void main(String[] args) throws IOException {
        SpringApplication.run(InvoicingSystemApplication.class, args);
    }

}

